import { PortfolioItem } from "@/types";

export const portfolioData: PortfolioItem[] = [
  {
    id: "apex-healthcare",
    slug: "apex-multispecialty-clinic",
    title: "Apex Multi-Specialty Clinic & Diagnostics",
    client: "Apex Healthcare Group",
    industry: "Healthcare / Clinics",
    location: "Indiranagar, Bengaluru",
    serviceCategory: "Technology",
    summary: "Built a high-speed doctor booking portal with automated WhatsApp reminders and Local 3-Pack SEO.",
    challenge: "High patient appointment no-shows and an outdated website that lost local search ranking to nearby private hospitals.",
    solution: "Developed a modern Next.js booking engine with instant slot availability, zero-login booking, automated WhatsApp reminders, and structured doctor schema markup.",
    results: [
      { label: "No-Show Reduction", value: "-68%" },
      { label: "Monthly New Patient Inquiries", value: "+180" },
      { label: "Google Maps Rank", value: "#1 for Specialist Care" },
      { label: "Page Load Speed", value: "0.6s" },
    ],
    tags: ["Next.js", "WhatsApp Cloud API", "Local SEO", "Healthcare"],
    testimonial: {
      quote: "PL Creations transformed our clinic's digital presence. Our front-desk phone calls dropped by 50% while our daily OPD consultations doubled.",
      author: "Dr. Arvind Rao",
      role: "Medical Director, Apex Healthcare",
    },
  },
  {
    id: "greenwood-academy",
    slug: "greenwood-international-school",
    title: "Greenwood Global School Admissions Engine",
    client: "Greenwood Educational Trust",
    industry: "Schools & Education",
    location: "Whitefield, Bengaluru",
    serviceCategory: "Digital Growth",
    summary: "Created an end-to-end digital admissions funnel and hyper-local Meta campaigns for preschool and primary admissions.",
    challenge: "Under-enrollment in kindergarten and primary classes with heavy reliance on printed paper brochures.",
    solution: "Designed an interactive virtual campus tour landing page, automated WhatsApp brochure downloads, and radius-targeted Meta ads for parents.",
    results: [
      { label: "Admissions Target Achieved", value: "115%" },
      { label: "Qualified Parent Leads", value: "480+" },
      { label: "Cost Per Lead Reduction", value: "-73%" },
    ],
    tags: ["Admission Funnel", "Meta Ads", "Parent Portal", "Education"],
    testimonial: {
      quote: "The admission response this year was phenomenal. We closed our nursery admissions 3 weeks ahead of schedule thanks to PL Creations.",
      author: "Meenakshi Sundaram",
      role: "Principal, Greenwood Global",
    },
  },
  {
    id: "urban-stay-pg",
    slug: "urbanstay-luxury-coliving",
    title: "UrbanStay Co-Living Network",
    client: "UrbanStay Hospitality",
    industry: "PGs & Co-Living",
    location: "Koramangala & HSR Layout, Bengaluru",
    serviceCategory: "Technology",
    summary: "Engineered a live bed inventory system, WhatsApp UPI rent collection, and local search dominance.",
    challenge: "High tenant turnover and lost rental revenue due to empty beds and manual offline rent collections across 6 buildings.",
    solution: "Built a customized web booking portal with real-time bed availability, automated WhatsApp payment links, and biometric entry sync.",
    results: [
      { label: "Occupancy Rate Maintained", value: "98.5%" },
      { label: "Rent Delay Drop", value: "-80%" },
      { label: "Broker Commission Saved", value: "Significant" },
    ],
    tags: ["Property Management", "WhatsApp Automation", "Local SEO", "Hostels"],
    testimonial: {
      quote: "PL Creations automated our entire tenant onboarding and rent collection pipeline. Our buildings stay full year-round.",
      author: "Rajesh Gowda",
      role: "Founder, UrbanStay",
    },
  },
];
