import { TestimonialItem } from "@/types";

export const testimonialsData: TestimonialItem[] = [
  {
    id: "test-1",
    name: "Dr. Arvind Rao",
    role: "Medical Director",
    company: "Apex Multi-Specialty Clinic",
    location: "Indiranagar, Bengaluru",
    content: "PL Creations built our patient booking engine and solved our no-show challenge completely. Our daily consultation slots are now consistently booked out 3 days in advance.",
    rating: 5,
    highlightMetric: "68% Drop in Patient No-Shows",
  },
  {
    id: "test-2",
    name: "Meenakshi Sundaram",
    role: "Principal & Trustee",
    company: "Greenwood Global School",
    location: "Whitefield, Bengaluru",
    content: "Their targeted parent lead generation campaign and campus CCTV setup for our school exceeded all expectations. We hit our annual intake capacity weeks before the academic term started.",
    rating: 5,
    highlightMetric: "480+ Qualified Admissions Leads",
  },
  {
    id: "test-3",
    name: "Rajesh Gowda",
    role: "Founder & Managing Director",
    company: "UrbanStay Hospitality & PGs",
    location: "Koramangala, Bengaluru",
    content: "Managing 6 PG buildings in Bengaluru was chaotic before PL Creations set up our biometric access control, CCTV monitoring, and WhatsApp automated rent payment systems.",
    rating: 5,
    highlightMetric: "98.5% Occupancy Maintained",
  },
  {
    id: "test-4",
    name: "Venkatesh Murthy",
    role: "Managing Director",
    company: "VoltCraft Switchgear",
    location: "Peenya Industrial Area, Bengaluru",
    content: "Their B2B outbound engine connected us with procurement heads across Karnataka and Tamil Nadu. The direct inquiries have significantly expanded our verified sales pipeline.",
    rating: 5,
    highlightMetric: "Enterprise Pipeline Growth",
  },
  {
    id: "test-5",
    name: "Ananya Hegde",
    role: "Managing Partner",
    company: "Swarna Fine Jewellery",
    location: "Jayanagar, Bengaluru",
    content: "The footfall we received from their hyper-local Google Maps and Instagram campaigns during festival season was incredible. A true high-velocity technology and growth partner!",
    rating: 5,
    highlightMetric: "54% Increase in Walk-ins",
  },
  {
    id: "test-6",
    name: "Karthik Narayanan",
    role: "Co-Founder & CEO",
    company: "Zenith Technologies",
    location: "Electronic City, Bengaluru",
    content: "The sheer speed and engineering standard of our new Next.js 15 web application shocked our board. We saw an immediate 125% increase in product demo bookings within the first month.",
    rating: 5,
    highlightMetric: "125% Lift in Demo Bookings",
  },
];
